catalog/urls.py
from django.conf import settings
from django.template.defaulttags import url
from django.urls import path, include, re_path
from django.views.i18n import JavaScriptCatalog
from django.views.static import serve
from django.contrib import admin

from . import views
from .views import CustomGalleryListView, CustomPhotoDetailView

urlpatterns = [path('admin/', admin.site.urls),
               path('', views.index, name='index'),
               path('senior_about/', views.senior_about, name='senior_about'),
               path('about/', views.about, name='about'),
               path('family_about/', views.family_about, name='family_about'),
               path('calendar/', views.calendar, name="calendar"),
               path('couples_enagagements_about', views.couples_engagements_about, name='couples_engagements_about'),
               path('calendar/<int:pk>', views.CalendarView.as_view(), name='couples_engagements_calendar'),
               path('cart/', views.view_cart, name='view_cart'),
               path('payment/', include('payments.urls')),
               path('create_booking/', views.create_booking, name='create_booking'),
               path('booking/', include('booking.urls'), name='booking'),
               path('bookings/', include('events.urls'), name='events'),
               path('members/', include('members.urls'), name='members'),
               path('portfolio/', CustomGalleryListView.as_view(), name='custom_gallery_list'),
               path('portfolio/photologue/<slug>/', CustomPhotoDetailView.as_view(), name='photo-detail'),
               path('input_order_information/', views.create_booking, name="input_order_information"),  # new
                re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}), # serve media files when deployed
                re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}), # serve static files when deployed
               ]

# Pages we need
# Index.html homepage with about us, our mission, and view package types (kelli)
# create a senior portraits page that links to the calendar page, available on nav bar (kelli)
# create a booking calendar page for the senior portraits avaialble dates (Alex)
# create a wedding portraits page that links to the calendar page, available on nav bar (kelli)
# create a booking calendar page for the wedding portraits avaialble dates (Alex)
# create a couples & engagements portraits page that links to the calendar page, available on nav bar (kelli)
# create a booking calendar page for the couples/engagements portraits avaialble dates (Alex)
# create a page that shows that you have a portrait package in your cart (Erik)
# create a page that allows you to input order information (Erik)
# create a page that shows that the booking was confirmed and that gives you a randomized confirmation number (Andrew)

events/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # Path Converters
    # int: numbers
    # str: strings
    # path: whole urls /
    # slug: hyphen-and_underscores_stuff
    # UUID: universally unique identifier

    path('', views.home, name="home"),
    path('<int:year>/<str:month>/', views.home, name="home"),
    path('bookings', views.all_events, name="list-events"),
    path('add_package', views.add_package, name='add-package'),
    path('list_packages', views.list_packages, name='list-packages'),
    path('show_package/<package_id>', views.show_package, name='show-package'),
    path('search_packages', views.search_packages, name='search-packages'),
    path('update_package/<package_id>', views.update_package, name='update-package'),
    path('update_booking/<event_id>', views.update_event, name='update-event'),
    path('add_booking', views.add_event, name='add-event'),
    path('delete_booking/<event_id>', views.delete_event, name='delete-event'),
    path('delete_package/<package_id>', views.delete_package, name='delete-package'),
    path('package_text', views.package_text, name='package_text'),
    path('package_csv', views.package_csv, name='package_csv'),
    path('package_pdf', views.package_pdf, name='package_pdf'),
    path('my_bookings', views.my_events, name='my_events'),
    path('search_bookings', views.search_events, name='search_events'),
    path('admin_approval', views.admin_approval, name='admin_approval'),
    path('package_bookings/<package_id>', views.package_events, name='package-events'),
    path('show_booking/<event_id>', views.show_event, name='show-event'),
]

locallibrary_pps/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.template.defaulttags import url
from django.urls import path, include, re_path
from photologue import sitemaps
from django.views.static import serve
from photologue.sitemaps import GallerySitemap, PhotoSitemap

import booking

sitemaps = {
            'photologue_galleries': GallerySitemap,
            'photologue_photos': PhotoSitemap,
            }

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('booking/', include('booking.urls')),
                  path('members/', include('members.urls')),
                  path('members/', include('django.contrib.auth.urls')),
                  path('user', include('members.urls')),
                  path('', include('catalog.urls')),
                  path('', include('events.urls')),
                  re_path(r'^photologue/', include('photologue.urls', namespace='photologue')),
                  path(
                      "sitemap.xml",
                      sitemap,
                      {"sitemaps": sitemaps},
                      name="django.contrib.sitemaps.views.sitemap",
                  ),
                  # re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
                  re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),

              ] + static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models
from django.urls import reverse
from django import forms


class PhotographySession(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.name


class Client(models.Model):
    client_id = models.CharField(max_length=200, primary_key=True)
    f_name = models.CharField(max_length=200)
    l_name = models.CharField(max_length=200)
    email = models.EmailField(max_length=50, blank=True, null=True)

    def __str__(self):
        return f'{self.fname} {self.lname}'


class Package(models.Model):
    package_id = models.CharField(max_length=200, primary_key=True)
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    duration = models.DateField()

    def __str__(self):
        return self.name


class Booking(models.Model):
    BOOKING_STATUS_CHOICES = [
        ('Approved', 'Approved'),
        ('Needs Rescheduled', 'Needs Rescheduled'),
        ('Pending Approval', 'Pending Approval')
    ]

    booking_id = models.CharField(max_length=200, primary_key=True)
    booking_datetime = models.DateTimeField()
    status = models.CharField(max_length=20, choices=BOOKING_STATUS_CHOICES, default='Pending Approval')
    created_date = models.DateTimeField()
    last_updated = models.DateTimeField()
    package = models.ForeignKey(Package, on_delete=models.CASCADE)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)

    def __str__(self):
        return self.booking_id

    def get_absolute_url(self):
        return reverse('calendar', args=[str(self.id)])


class Photo(models.Model):
    photo_id = models.CharField(max_length=200, primary_key=True)
    file_path = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)
    package = models.ForeignKey(Booking, on_delete=models.CASCADE, related_name='photos')

    def __str__(self):
        return self.photo_id

events/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date


class Package(models.Model):
    name = models.CharField('Package Name', max_length=120)
    address = models.CharField(max_length=300)
    zip_code = models.CharField('Zip Code', max_length=15)
    phone = models.CharField('Contact Phone', max_length=25, blank=True)
    web = models.URLField('Website Address', blank=True)
    email_address = models.EmailField('Email Address', blank=True)
    owner = models.IntegerField("Package Owner", blank=False, default=1)
    package_image = models.ImageField(null=True, blank=True, upload_to="images/")

    def __str__(self):
        return self.name


class MyClubUser(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField('User Email')

    def __str__(self):
        return self.first_name + ' ' + self.last_name


class Event(models.Model):
    name = models.CharField('Event Name', max_length=120)
    event_date = models.DateTimeField('Event Date')
    package = models.ForeignKey(Package, blank=True, null=True, on_delete=models.CASCADE)
    # package = models.CharField(max_length=120)
    manager = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL)
    description = models.TextField(blank=True)
    attendees = models.ManyToManyField(MyClubUser, blank=True)
    approved = models.BooleanField('Approved', default=False)

    def __str__(self):
        return self.name

    @property
    def Days_till(self):
        today = date.today()
        days_till = self.event_date.date() - today
        days_till_stripped = str(days_till).split(",", 1)[0]
        return days_till_stripped

    @property
    def Is_Past(self):
        today = date.today()
        if self.event_date.date() < today:
            thing = "Past"
        else:
            thing = "Future"
        return thing

catalog/forms.py
from django import forms


class OrderForm(forms.Form):
    product_name = forms.CharField(label='Product Name')
    amount = forms.DecimalField(label='Amount')

events/forms.py
from django import forms
from django.forms import ModelForm
from .models import Package, Event


# Admin SuperUser Event Form
class EventFormAdmin(ModelForm):
    class Meta:
        model = Event
        fields = ('name', 'event_date', 'package', 'manager', 'attendees', 'description')
        labels = {
            'name': '',
            'event_date': 'YYYY-MM-DD HH:MM:SS',
            'package': 'Package',
            'manager': 'Photographer',
            'attendees': 'Attendees',
            'description': '',
        }
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Event Name'}),
            'event_date': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Event Date'}),
            'package': forms.Select(attrs={'class': 'form-select', 'placeholder': 'Package'}),
            'manager': forms.Select(attrs={'class': 'form-select', 'placeholder': 'Manager'}),
            'attendees': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Attendees'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Description'}),
        }


# User Event Form
class EventForm(ModelForm):
    class Meta:
        model = Event
        fields = ('name', 'event_date', 'package', 'attendees', 'description')
        labels = {
            'name': '',
            'event_date': 'YYYY-MM-DD HH:MM:SS',
            'package': 'Package',
            'attendees': 'Notes',
            'description': '',
        }
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Booking Name'}),
            'event_date': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Booking Date'}),
            'package': forms.Select(attrs={'class': 'form-select', 'placeholder': 'Package'}),
            'attendees': forms.SelectMultiple(attrs={'class': 'form-control', 'placeholder': 'Notes'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Description'}),
        }


# Create a package form
class PackageForm(ModelForm):
    class Meta:
        model = Package  # This should match the model name from models.py
        fields = ('name', 'address', 'zip_code', 'phone', 'web', 'email_address', 'package_image')
        labels = {
            'name': '',
            'address': '',
            'zip_code': '',
            'phone': '',
            'web': '',
            'email_address': '',
            'package_image': '',
        }
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Package Name'}),
            'address': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Address'}),
            'zip_code': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Zip Code'}),
            'phone': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Phone'}),
            'web': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Web Address'}),
            'email_address': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
            # Ensure you have the corresponding widget for 'package_image' if it needs to be customized.
        }

catalog/views.py
import datetime

import stripe as stripe
from django.shortcuts import render
from django.views import generic
from photologue.models import Gallery
from photologue.views import GalleryListView, PhotoDetailView

from .forms import OrderForm
from .models import PhotographySession, Booking
from django.conf import settings
from django.http import JsonResponse
from django.http import HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt


class CustomGalleryListView(GalleryListView):
    template_name = 'photologue/gallery_list.html'

    def get_queryset(self):
        return Gallery.objects.filter(title__icontains='')


class CustomPhotoDetailView(PhotoDetailView):
    template_name = 'photologue/photo_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


def index(request):
    context = {

    }

    return render(request, 'index.html', context=context)


def about(request):
    return render(request, 'about.html')


def senior_about(request):
    return render(request, 'senior_about.html')


def family_about(request):
    return render(request, 'family_about.html')


def couples_engagements_about(request):
    return render(request, 'couples_engagements_about.html')


def calendar(request):
    return render(request, 'calendar.html')


class CalendarView(generic.DetailView):
    model = Booking


def view_cart(request):
    cart = request.session.get('cart', [])  # Get the cart from the session
    sessions_in_cart = PhotographySession.objects.filter(id__in=cart)

    return render(request, 'shopping_cart.html', {'sessions_in_cart': sessions_in_cart})


stripe.api_key = settings.STRIPE_SECRET_KEY


def create_booking(request):
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            product_name = form.cleaned_data['product_name']
            amount = form.cleaned_data['amount'] * 100  # Convert to cents

            # Create a Stripe PaymentIntent
            payment_intent = stripe.PaymentIntent.create(
                amount=int(amount),
                currency='usd',
                description=product_name
            )

            return render(request, 'payment.html', {'client_secret': payment_intent.client_secret})

    else:
        form = OrderForm()

    return render(request, 'order_information_input.html', {'form': form})


def calendar_view(request):
    month = request.GET.get('month', None)
    year = request.GET.get('year', None)

    if month and year:
        currentDate = datetime.date(int(year), int(month), 1)
    else:
        currentDate = datetime.date.today()

    bookings_for_month = Booking.objects.filter(date__month=currentDate.month, date__year=currentDate.year)

    booked_dates = [b.date.day for b in bookings_for_month]

    return render(request, 'calendar.html', {'booked_dates': booked_dates, 'current_month': currentDate.month,
                                             'current_year': currentDate.year})

    # return JsonResponse({
    #     'booked_dates': booked_dates,
    #     'current_month': currentDate.month,
    #     'current_year': currentDate.year
    # })

catalog/templates/events/add_package.html
{% extends 'events/base.html' %}

{% block content %}
    {% if user.is_authenticated %}
        <center>
            <h1>Add New Photo Package</h1>
            <br/><br/>
            {% if submitted %}
                Your Package Was Submitted Successfully!

            {% else %}

                <form action="" method=POST enctype="multipart/form-data">
                    {% csrf_token %}

                    {{ form.as_p }}

                    <input type="submit" value="Submit" class="btn btn-secondary">

                </form>
            {% endif %}
        </center>
    {% else %}
        <h1>Sorry! You Must Be Logged In To View This Page...</h1>

        <a href="{% url 'login' %}">Login Here</a>
    {% endif %}

{% endblock %}

catalog/templates/events/admin_approval.html
{% extends 'events/base.html' %}

{% block content %}


    <h1>Admin Dashboard</h1>
    <br/><br/>
    <form action="" method=POST>
        {% csrf_token %}

        <div class="card">
            <div class="card-header">
                Availability - Packages - User Count List
            </div>
            <div class="card-body">
                <p class="card-text">Available Bookings: {{ event_count }}</p>
                <p class="card-text">Package Count: {{ package_count }}</p>
                <p class="card-text">User Count: {{ user_count }}</p>

            </div>
        </div>
        <br/><br/>

        <table class="table table-striped table-hover table-bordered">
            <thead>
            <tr>
                <th scope="col">Package Name</th>
                <th scope="col">Availability</th>
            </tr>
            </thead>
            <tbody>
            {% for package in package_list %}
                <tr>
                    <td>
                        <a href="{% url 'show-package' package.id %}">{{ package }}</a>
                    </td>
                    <td>
                        <a href="{% url 'package-events' package.id %}" class="btn btn-sm btn-secondary">List Availability</a>
                    </td>
                </tr>
            {% endfor %}


            </tbody>
        </table>


        <br/><br/>
        <h1>Event Approval Form</h1>
        <br/>
        <table class="table table-striped table-hover table-bordered">
            <thead>
            <tr>
                <th scope="col">Event Name</th>
                <th scope="col">Aproved</th>
            </tr>
            </thead>
            <tbody>
            {% for event in event_list %}
                <tr>
                    <td>{{ event }}</td>
                    <td>
                        {% if event.approved %}
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" checked="checked"
                                       value={{ event.id }} name="boxes">
                            </div>
                        {% else %}
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" value={{ event.id }} name="boxes">
                            </div>
                        {% endif %}

                    </td>
                </tr>
            {% endfor %}


            </tbody>
        </table>

        <br/>
        <button class='btn btn-secondary' type="submit">Update Approval</button>



{% endblock %}

catalog/templates/events/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300;400;500;600;700&display=swap"
          rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
    <script src="{% static 'calendar.js' %}" defer></script>
    <title>Pixel Perfect Studios |  Bookings</title>
</head>
<body>
{% include 'header.html' %}
<br/>
<div class="container">
    {% if messages %}
        {% for message in messages %}

            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>

        {% endfor %}
    {% endif %}

    {% block content %}
    {% endblock %}
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
        crossorigin="anonymous"></script>

</body>
</html>

catalog/templates/events/booking_list.html
{% extends 'events/base.html' %}

{% block content %}
    <head>
        <title>Pixel Perfect Studios | Available Bookings</title>
    </head>

    <h1 class="title" style="font-weight: 500;">Available Bookings</h1>
    <br/>



    {% comment %}{% if event.approved %}{% endcomment %}

    {% for event in event_list %}
        <div class="card">

            <div class="card-header">
                {{ event }}
            </div>

            <div class="card-body">
                <h5 class="card-title">Package: {{ event.package }}</h5>
                <ul class="card-text">
                    <li>Date: {{ event.event_date }}</li>
                    <li>Days Till Booking: {{ event.Days_till }}</li>
                    <li>Occurred: {{ event.Is_Past }}</li>
                    <li>Package Website: {{ event.package.web }}</li>
                    <li>Photographer: {{ event.manager }}</li>
                    <li>Description: {{ event.description }}</li>
                    <li>Approved: {{ event.approved }}</li>
                    <li>Notes:<br/>
                        {% for user in event.attendees.all %}
                            {{ user }}<br/>

                        {% endfor %}
                    </li>
                </ul>
            </div>
            {% if user.is_authenticated %}
                <div class="card-footer text-muted">

                    <a href="{% url 'update-event' event.id %}" class="btn btn-outline-primary btn-sm">Update
                        Booking</a>

                    <a href="{% url 'delete-event' event.id %}" class="btn btn-outline-danger btn-sm">Delete
                        Booking</a>

                </div>
            {% endif %}
                {% comment %}{% endif %}{% endcomment %}
        </div>

        <br/><br/>

    {% endfor %}

    {% comment %}{% endif %}{% endcomment %}



{% endblock %}

catalog/templates/events/home.html
{% extends 'events/base.html' %}

{% block content %}
    <div style="text-align: center;">
        <h1>Welcome Back!</h1>
        <h3>Bookings for <strong>{{ month }} {{ year }}</strong></h3>

        <p style="font-size: 13px;">As of {{ time }}</p>
        <br/><br/>
        <div class="calendar" style="margin: -10px auto;">
            <div class="header" style="background-color: #ffd234; color: #1c212d;">
                <span class="prev">←</span>
                <span class="month-year">October 2023</span>
                <span class="next">→</span>
            </div>
            <div class="days">
                <div class="day">Sun</div>
                <div class="day">Mon</div>
                <div class="day">Tue</div>
                <div class="day">Wed</div>
                <div class="day">Thu</div>
                <div class="day">Fri</div>
                <div class="day">Sat</div>
            </div>
            <div class="dates">
                <!-- Dates will be filled here using Django -->
                {% for date in dates %}
                    <div class="date">{{ date }}</div>
                {% endfor %}
            </div>
        </div>
        <br/><br/>
    </div>
    <h3>Bookings This Month:</h3>

    {% if event_list %}
        {% for event in event_list %}
            <div class="card">
                <div class="card-header">
                    {{ event }}
                </div>
                <div class="card-body">
                    <h5 class="card-title">Package: {{ event.package }}</h5>
                    <p class="card-text">
                    <ul>
                        <li>Date: {{ event.event_date }}</li>

                        <li>Package Info: {{ event.package.web }}</li>
                        <li>Photographer: {{ event.manager }}</li>
                        <li>Description: {{ event.description }}</li>
                        <li>Addtl. Notes:<br/>
                            {% for user in event.attendees.all %}
                                {{ user }}<br/>
                            {% endfor %}
                        </li>
                    </ul>


                    </p>
                </div>
                {% if user.is_authenticated %}
                    {% if user == event.manager %}
                        <div class="card-footer text-muted">

                            <a href="{% url 'update-event' event.id %}" class="btn btn-outline-secondary btn-sm">Update
                                Event</a>

                            <a href="{% url 'delete-event' event.id %}" class="btn btn-outline-danger btn-sm">Delete
                                Event</a>

                        </div>
                    {% endif %}
                {% endif %}
            </div>
            <br/>
        {% endfor %}

    {% else %}
        Sorry, no available bookings this month.
    {% endif %}

    <center>
        <br/><br/><br/><br/>
        Copyright (c) {{ current_year }} | Pixel Perfect Studios

    </center>
{% endblock %}

catalog/templates/events/my_bookings.html
{% extends 'events/base.html' %}

{% block content %}

    <h2>My Bookings</h2>
    <br/>

    {% for event in events %}

        <div class="card">
            <div class="card-header">
                {{ event }}
            </div>
            <div class="card-body">
                <h5 class="card-title">Package: {{ event.package }}</h5>
                <p class="card-text">
                <ul>
                    <li>Date: {{ event.event_date }}</li>

                    <li>Package Website: {{ event.package.web }}</li>
                    <li>Manager: {{ event.manager }}</li>
                    <li>Description: {{ event.description }}</li>
                    <li>Attendees:<br/>
                        {% for user in event.attendees.all %}
                            {{ user }}<br/>
                        {% endfor %}
                    </li>
                </ul>


                </p>
            </div>
            {% if user.is_authenticated %}
                {% if user == event.manager %}
                    <div class="card-footer text-muted">

                        <a href="{% url 'update-event' event.id %}" class="btn btn-outline-secondary btn-sm">Update
                            Booking</a>

                        <a href="{% url 'delete-event' event.id %}" class="btn btn-outline-danger btn-sm">Delete
                            Booking</a>

                    </div>
                {% endif %}
            {% endif %}
        </div>





        <br/><br/>



    {% endfor %}




{% endblock %}

catalog/templates/events/package.html
{% extends 'events/base.html' %}

{% block content %}

    <section>
        <h1>Available Packages</h1>
        <br/>
        <table class="table table-striped table-hover table-bordered">
            {% for package in packages %}
                <tr>
                    <td>
                        <a href="{% url 'show-package' package.id %}" class="title" style="font-size: 22px!important;">{{ package }}</a>
                    </td>
                    {% if user.is_authenticated %}
                        <td align="right">
                            <a href="{% url 'update-package' package.id %}" class="btn btn-outline-secondary btn-sm">Update</a>

                            <a href="{% url 'delete-package' package.id %}" class="btn btn-outline-danger btn-sm">Delete</a>
                        </td>
                    {% endif %}
                </tr>
            {% endfor %}
        </table>
    </section>
    <br/></br/>
    <!--
{{ packages }}<br/>
Has Previous: {{ packages.has_previous }}<br/>
Has Next: {{ packages.has_next }}<br/>
Current Page: {{ packages.number }}<br/>
Number of Pages: {{ packages.paginator.num_pages }}<br/>
<hr><br/><br/>
-->

    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">


            {% if packages.has_previous %}
                <li class="page-item"><a class="page-link" href="?page=1">&laquo First</a></li>

                <li class="page-item"><a class="page-link" href="?page={{ packages.previous_page_number }}">Previous</a>
                </li>

            {% endif %}

            <!--
<li class="page-item disabled"><a href="#" class="page-link">Page {{ packages.number }} of {{ packages.paginator.num_pages }}</a></li>
-->

            {% for i in nums %}
                <li class="page-item"><a class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a>
                </li>

            {% endfor %}


            {% if packages.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ packages.next_page_number }}">Next</a></li>

                <li class="page-item"><a class="page-link" href="?page={{ packages.paginator.num_pages }}">Last &raquo</a>
                </li>

            {% endif %}

        </ul>
    </nav>
    <br/>

{% endblock %}

catalog/templates/events/package_bookings.html
{% extends 'events/base.html' %}

{% block content %}

    <h1>List Events</h1>

    {% for event in events %}
        <a href="{% url 'show-event' event.id %}">{{ event }}</a><br/>
    {% endfor %}

{% endblock %}

catalog/templates/events/update_booking.html
{% extends 'events/base.html' %}

{% block content %}
    {% if user.is_authenticated %}
        {% if user == event.manager %}

            <h1>Update Event...</h1>
            <br/>
            <form action="" method=POST>
            {% csrf_token %}
            {{ form.as_p }}
            <br/>
            <input type="submit" value="Update" class="btn btn-secondary">

        {% else %}
            <h2>Access Denied</h2>
            <p>Only the event's Manager can update this event...</p>

            Logged In User:  {{ user }}
            <br/>
            Event Manager: {{ event.manager }}
            <br/>
        {% endif %}


    {% else %}
        <h1>Sorry! You Must Be Logged In To View This Page...</h1>

        <a href="{% url 'login' %}">Login Here</a>
    {% endif %}



{% endblock %}